apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cloudgallery
  name: backend-config
data:
  NODE_ENV: "production"
  PORT: "5000"
  FRONTEND_URL: "https://gallery.yourdomain.com"
  REDIS_URL: "redis://default:M5mO9fBafgrXKOddbDAbEDMkLqX82s1e@redis-15920.crce283.ap-south-1-2.ec2.cloud.redislabs.com:15920"
  AZURE_CONTAINER_NAME: "cg-gallery"
