name: CI Pipeline

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Frontend
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cloudgalleryfrontend:latest -t ${{ secrets.DOCKER_USERNAME }}/cloudgalleryfrontend:${{ github.run_number }} ./frontend

      - name: Push Frontend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cloudgalleryfrontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cloudgalleryfrontend:${{ github.run_number }}


      - name: Build Backend
        run: |   
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cloudgallerybackend:latest -t ${{ secrets.DOCKER_USERNAME }}/cloudgallerybackend:${{ github.run_number }}  ./backend

      - name: Push Backend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cloudgallerybackend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cloudgallerybackend:${{ github.run_number }} 


      - name: Triggers Jenkins
        if: success()
        run: |
          curl -X POST "http://${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}@135.235.195.86:8080/job/Cloud-Gallery-pipeline/buildWithParameters?IMAGE_TAG=${{ github.run_number }}"